### ISSUE TITLE
您好，发现一个问题，空指针崩溃

### ISSUE THREAD

**Issue by XingAndroid** [jaychou2012/SmartTVLib#1]
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter child
2022-04-20 21:12:38.535 3941-3941/com.panda.course E/DEBUG:     at com.panda.course.ui.activity.CourseActivity$j.b(Unknown Source:2)
2022-04-20 21:12:38.536 3941-3941/com.panda.course E/DEBUG:     at com.tandong.smarttv.view.GridLayoutManager.fireOnChildViewHolderSelectedAndPositioned(SourceFile:884)
2022-04-20 21:12:38.538 3941-3941/com.panda.course E/DEBUG:     at com.tandong.smarttv.view.GridLayoutManager.dispatchChildSelectedAndPositioned(SourceFile:991)
2022-04-20 21:12:38.540 3941-3941/com.panda.course E/DEBUG:     at com.tandong.smarttv.view.GridLayoutManager.onLayoutChildren(SourceFile:2279)
2022-04-20 21:12:38.541 3941-3941/com.panda.course E/DEBUG:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:4309)
2022-04-20 21:12:38.544 3941-3941/com.panda.course E/DEBUG:     at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:4012)
2022-04-20 21:12:38.545 3941-3941/com.panda.course E/DEBUG:     at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:4578)
2022-04-20 21:12:38.547 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.548 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.550 3941-3941/com.panda.course E/DEBUG:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
2022-04-20 21:12:38.552 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.554 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.557 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2022-04-20 21:12:38.559 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2022-04-20 21:12:38.562 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.563 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.565 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2022-04-20 21:12:38.567 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2022-04-20 21:12:38.568 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.569 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.570 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
2022-04-20 21:12:38.571 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2022-04-20 21:12:38.572 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2022-04-20 21:12:38.573 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.575 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.576 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2022-04-20 21:12:38.580 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2022-04-20 21:12:38.581 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.582 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.583 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
2022-04-20 21:12:38.584 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2022-04-20 21:12:38.585 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2022-04-20 21:12:38.585 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.586 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.587 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2022-04-20 21:12:38.587 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2022-04-20 21:12:38.588 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.589 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.590 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
2022-04-20 21:12:38.591 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2022-04-20 21:12:38.592 3941-3941/com.panda.course E/DEBUG:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2022-04-20 21:12:38.594 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.595 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.596 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2022-04-20 21:12:38.596 3941-3941/com.panda.course E/DEBUG:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2022-04-20 21:12:38.597 3941-3941/com.panda.course E/DEBUG:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
2022-04-20 21:12:38.598 3941-3941/com.panda.course E/DEBUG:     at android.view.View.layout(View.java:22844)
2022-04-20 21:12:38.599 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
2022-04-20 21:12:38.599 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)
2022-04-20 21:12:38.600 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
2022-04-20 21:12:38.602 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
2022-04-20 21:12:38.603 3941-3941/com.panda.course E/DEBUG:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
2022-04-20 21:12:38.604 3941-3941/com.panda.course E/DEBUG:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
2022-04-20 21:12:38.605 3941-3941/com.panda.course E/DEBUG:     at android.view.Choreographer.doCallbacks(Choreographer.java:796)
2022-04-20 21:12:38.606 3941-3941/com.panda.course E/DEBUG:     at android.view.Choreographer.doFrame(Choreographer.java:731)
2022-04-20 21:12:38.607 3941-3941/com.panda.course E/DEBUG:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
2022-04-20 21:12:38.608 3941-3941/com.panda.course E/DEBUG:     at android.os.Handler.handleCallback(Handler.java:938)
2022-04-20 21:12:38.609 3941-3941/com.panda.course E/DEBUG:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-04-20 21:12:38.610 3941-3941/com.panda.course E/DEBUG:     at android.os.Looper.loop(Looper.java:223)
2022-04-20 21:12:38.610 3941-3941/com.panda.course E/DEBUG:     at android.app.ActivityThread.main(ActivityThread.java:7660)
2022-04-20 21:12:38.611 3941-3941/com.panda.course E/DEBUG:     at java.lang.reflect.Method.invoke(Native Method)
2022-04-20 21:12:38.613 3941-3941/com.panda.course E/DEBUG:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2022-04-20 21:12:38.614 3941-3941/com.panda.course E/DEBUG:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by jaychou2012** [comment]
E-MAIL 已收到。
